# Manager Match Data — Validation Notebook

Quick check to see whether `transfermarkt-datasets` is a viable source for the *a corto muso* article.

**What this notebook does:**
1. Downloads `games.csv` from the `transfermarkt-datasets` public R2 bucket
2. Checks how each manager's name appears in the data (spelling matters)
3. Counts matches per manager — total, domestic league, and Big 5 only
4. Runs a first sanity check on Allegri's scoreline distribution

## 1. Load `games.csv`

Source: [dcaribou/transfermarkt-datasets](https://github.com/dcaribou/transfermarkt-datasets) — ~88k matches, refreshed weekly.

Using `requests` with a browser User-Agent because the R2 bucket blocks pandas' default `urllib` agent. The `.gz` file needs `compression='gzip'` explicitly.

In [1]:
import requests, io, pandas as pd

GAMES_URL = "https://pub-e682421888d945d684bcae8890b0ec20.r2.dev/data/games.csv.gz"

response = requests.get(GAMES_URL, headers={"User-Agent": "Mozilla/5.0"})
response.raise_for_status()

games = pd.read_csv(io.BytesIO(response.content), compression="gzip")

print(f"Rows    : {len(games):,}")
print(f"Columns : {list(games.columns)}")
print(f"Seasons : {sorted(games['season'].unique())}")
print(f"Dates   : {games['date'].min()}  →  {games['date'].max()}")

Rows    : 88,783
Columns : ['game_id', 'competition_id', 'season', 'round', 'date', 'home_club_id', 'away_club_id', 'home_club_goals', 'away_club_goals', 'home_club_position', 'away_club_position', 'home_club_manager_name', 'away_club_manager_name', 'stadium', 'attendance', 'referee', 'url', 'home_club_formation', 'away_club_formation', 'home_club_name', 'away_club_name', 'aggregate', 'competition_type']
Seasons : [np.int64(2005), np.int64(2007), np.int64(2009), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]
Dates   : 2006-06-09  →  2026-05-26

In [2]:
# Quick look at a raw row to confirm manager columns are present
games[[
    'date', 'competition_id', 'competition_type',
    'home_club_name', 'home_club_goals',
    'away_club_name', 'away_club_goals',
    'home_club_manager_name', 'away_club_manager_name'
]].head(3)

,date,competition_id,competition_type,home_club_name,home_club_goals,away_club_name,away_club_goals,home_club_manager_name,away_club_manager_name
0,2010-06-26,FIWC,national_team_competition,Uruguay,2,South Korea,1,Óscar Tabárez,Jung-moo Huh
1,2010-06-27,FIWC,national_team_competition,Argentina,3,Mexico,1,Diego Maradona,Javier Aguirre
2,2010-06-26,FIWC,national_team_competition,United States,1,Ghana,2,Bob Bradley,Milovan Rajevac

## 2. Manager list

Exact Transfermarkt name strings, confirmed by the lookup in section 3.
Simone Inzaghi chosen over Filippo.

In [3]:
# Keys   = display names used throughout the notebook
# Values = exact strings as they appear in transfermarkt-datasets
MANAGER_NAMES = {
    "Massimiliano Allegri" : "Massimiliano Allegri",
    "Pep Guardiola"        : "Pep Guardiola",
    "José Mourinho"        : "José Mourinho",
    "Antonio Conte"        : "Antonio Conte",
    "Carlo Ancelotti"      : "Carlo Ancelotti",
    "Roberto De Zerbi"     : "Roberto De Zerbi",
    "Vincenzo Italiano"    : "Vincenzo Italiano",
    "Simone Inzaghi"       : "Simone Inzaghi",
}

## 3. Name lookup — what does Transfermarkt actually call them?

Searches by surname. Kept here for reference — confirmed clean on first run.
Ambiguities resolved: Carlo (not Davide) Ancelotti, Vincenzo (not Giancarlo) Italiano, Simone (not Filippo) Inzaghi.

In [4]:
all_names = pd.Series(
    list(games["home_club_manager_name"].dropna().unique()) +
    list(games["away_club_manager_name"].dropna().unique())
).unique()

print(f"Distinct manager name strings in dataset: {len(all_names)}\n")
print(f"{'Queried name':<35}  Matches found in data")
print("-" * 75)

for name in MANAGER_NAMES:
    surname = name.split()[-1]
    hits = [m for m in all_names if surname.lower() in str(m).lower()]
    print(f"{name:<35}  {hits}")

Distinct manager name strings in dataset: 7020

Queried name                         Matches found in data
---------------------------------------------------------------------------
Massimiliano Allegri                 ['Massimiliano Allegri']
Pep Guardiola                        ['Pep Guardiola']
José Mourinho                        ['José Mourinho']
Antonio Conte                        ['Antonio Conte']
Carlo Ancelotti                      ['Carlo Ancelotti', 'Davide Ancelotti']
Roberto De Zerbi                     ['Roberto De Zerbi']
Vincenzo Italiano                    ['Vincenzo Italiano', 'Giancarlo Italiano']
Simone Inzaghi                       ['Filippo Inzaghi', 'Simone Inzaghi']

## 4. Reshape to long form

Each raw row encodes both teams. We melt to one row per *(manager, match)*
so `goals_for` / `goals_against` are always from that manager's perspective.

In [5]:
KEEP = ["game_id", "date", "season", "competition_id", "competition_type"]

home = games[KEEP + [
    "home_club_name", "away_club_name",
    "home_club_goals", "away_club_goals",
    "home_club_manager_name"
]].copy()
home.columns = KEEP + ["club", "opponent", "goals_for", "goals_against", "manager"]
home["venue"] = "home"

away = games[KEEP + [
    "away_club_name", "home_club_name",
    "away_club_goals", "home_club_goals",
    "away_club_manager_name"
]].copy()
away.columns = KEEP + ["club", "opponent", "goals_for", "goals_against", "manager"]
away["venue"] = "away"

long = pd.concat([home, away], ignore_index=True)
long["goal_diff"] = long["goals_for"] - long["goals_against"]
long["result"]    = long["goal_diff"].map(
    lambda x: "W" if x > 0 else ("L" if x < 0 else "D")
)

print(f"Long-form rows: {len(long):,}  (should be ~2x the raw row count)")
long.head(3)

Long-form rows: 177,566  (should be ~2x the raw row count)

,game_id,date,season,competition_id,competition_type,club,opponent,goals_for,goals_against,manager,venue,goal_diff,result
0,1026846,2010-06-26,2009,FIWC,national_team_competition,Uruguay,South Korea,2,1,Óscar Tabárez,home,1,W
1,1026847,2010-06-27,2009,FIWC,national_team_competition,Argentina,Mexico,3,1,Diego Maradona,home,2,W
2,1027001,2010-06-26,2009,FIWC,national_team_competition,United States,Ghana,1,2,Bob Bradley,home,-1,L

## 5. Coverage check — Big 5 domestic leagues only

Competition codes confirmed from the data:
- `GB1` Premier League
- `IT1` Serie A
- `ES1` La Liga
- `L1`  Bundesliga
- `FR1` Ligue 1

Excluded: `TR1` (Mourinho at Fenerbahçe), `SA1` (Simone Inzaghi at Al-whatever), `PO1` (Mourinho at Porto/Sporting).

In [6]:
BIG5 = {"GB1", "IT1", "ES1", "L1", "FR1"}

rows = []
for label, tm_name in MANAGER_NAMES.items():
    mask_all      = (long["manager"] == tm_name) & (long["competition_type"] == "domestic_league")
    mask_big5     = mask_all & long["competition_id"].isin(BIG5)
    competitions  = long[mask_big5]["competition_id"].unique().tolist()
    rows.append({
        "manager"      : label,
        "all_domestic" : mask_all.sum(),
        "big5_only"    : mask_big5.sum(),
        "leagues"      : competitions,
    })

pd.DataFrame(rows)

                manager  all_domestic  big5_only                   leagues
0  Massimiliano Allegri           397        397                     [IT1]
1         Pep Guardiola           482        482                 [L1, GB1]
2         José Mourinho           445        377           [ES1, GB1, IT1]
3         Antonio Conte           345        345                [IT1, GB1]
4       Carlo Ancelotti           417        417  [FR1, ES1, L1, IT1, GB1]
5      Roberto De Zerbi           305        287           [IT1, GB1, FR1]
6     Vincenzo Italiano           228        228                     [IT1]
7        Simone Inzaghi           383        349                     [IT1]

## 6. Build the canonical dataset

Filter to Big 5, tag each row with the display manager name, save as parquet.

In [11]:
frames = []
for label, tm_name in MANAGER_NAMES.items():
    mask = (
        (long["manager"] == tm_name) &
        (long["competition_type"] == "domestic_league") &
        (long["competition_id"].isin(BIG5))
    )
    df = long[mask].copy()
    df["manager_label"] = label
    frames.append(df)

manager_matches = pd.concat(frames, ignore_index=True)

print(f"Total rows in manager_matches: {len(manager_matches):,}")
print(manager_matches["manager_label"].value_counts().to_string())

manager_matches.to_csv("./data/raw/manager_matches.csv", index=False)
print(f"Total rows in manager_matches: {len(manager_matches):,}")
print(manager_matches["manager_label"].value_counts().to_string())
print("\nSaved → manager_matches.csv")

Total rows in manager_matches: 2,882
manager_label
Pep Guardiola           482
Carlo Ancelotti         417
Massimiliano Allegri    397
José Mourinho           377
Simone Inzaghi          349
Antonio Conte           345
Roberto De Zerbi        287
Vincenzo Italiano       228
Total rows in manager_matches: 2,882
manager_label
Pep Guardiola           482
Carlo Ancelotti         417
Massimiliano Allegri    397
José Mourinho           377
Simone Inzaghi          349
Antonio Conte           345
Roberto De Zerbi        287
Vincenzo Italiano       228

Saved → manager_matches.csv

In [12]:
manager_matches.head()

,game_id,date,season,competition_id,competition_type,club,opponent,goals_for,goals_against,manager,venue,goal_diff,result,manager_label
0,2251270,2012-08-26,2012,IT1,domestic_league,Associazione Calcio Milan,UC Sampdoria,0,1,Massimiliano Allegri,home,-1,L,Massimiliano Allegri
1,2251286,2012-09-15,2012,IT1,domestic_league,Associazione Calcio Milan,Atalanta Bergamasca Calcio S.p.a.,0,1,Massimiliano Allegri,home,-1,L,Massimiliano Allegri
2,2251307,2012-09-26,2012,IT1,domestic_league,Associazione Calcio Milan,Cagliari Calcio,2,0,Massimiliano Allegri,home,2,W,Massimiliano Allegri
3,2251327,2012-10-07,2012,IT1,domestic_league,Associazione Calcio Milan,Football Club Internazionale Milano S.p.A.,0,1,Massimiliano Allegri,home,-1,L,Massimiliano Allegri
4,2251346,2012-10-27,2012,IT1,domestic_league,Associazione Calcio Milan,Genoa Cricket and Football Club,1,0,Massimiliano Allegri,home,1,W,Massimiliano Allegri

## 7. First look: Allegri scoreline distribution

The *a corto muso* thesis in its simplest form.
Confirmed on first run: 1-0 is his modal scoreline (64 matches, ~16% of all domestic league games).

In [8]:
allegri = manager_matches[manager_matches["manager_label"] == "Massimiliano Allegri"].copy()

print(f"Allegri Big 5 domestic league matches: {len(allegri)}")
print()
print("Result breakdown:")
print(allegri["result"].value_counts().to_frame("count"))
print()
print("Top 15 scorelines:")
(
    allegri
    .groupby(["goals_for", "goals_against"])
    .size()
    .reset_index(name="count")
    .assign(scoreline=lambda df: df["goals_for"].astype(str) + "-" + df["goals_against"].astype(str))
    .sort_values("count", ascending=False)
    .head(15)
    [["scoreline", "count"]]
    .reset_index(drop=True)
)

Allegri Big 5 domestic league matches: 397

Result breakdown:
        count
result
W         248
D          83
L          66

Top 15 scorelines:

   scoreline  count
0        1-0     64
1        2-0     52
2        1-1     42
3        2-1     40
4        3-0     31
5        0-1     25
6        3-1     23
7        2-2     20
8        1-2     19
9        0-0     18
10       3-2     11
11       4-0      9
12       0-2      8
13       4-1      6
14       4-2      6

In [10]:
guardiola = manager_matches[manager_matches["manager_label"] == "Pep Guardiola"].copy()

print(f"Guardiola Big 5 domestic league matches: {len(guardiola)}")
print()
print("Result breakdown:")
print(guardiola["result"].value_counts().to_frame("count"))
print()
print("Top 15 scorelines:")
(
    guardiola
    .groupby(["goals_for", "goals_against"])
    .size()
    .reset_index(name="count")
    .assign(scoreline=lambda df: df["goals_for"].astype(str) + "-" + df["goals_against"].astype(str))
    .sort_values("count", ascending=False)
    .head(15)
    [["scoreline", "count"]]
    .reset_index(drop=True)
)

Guardiola Big 5 domestic league matches: 482

Result breakdown:
        count
result
W         351
D          69
L          62

Top 15 scorelines:

   scoreline  count
0        2-0     57
1        3-1     48
2        2-1     48
3        1-0     48
4        3-0     38
5        1-1     31
6        4-0     30
7        5-0     21
8        1-2     19
9        4-1     19
10       0-0     17
11       2-2     16
12       0-2     14
13       0-1     12
14       5-1     10

## 8. Competition types reference

Useful reminder of what values `competition_type` takes.

In [9]:
games["competition_type"].value_counts()

competition_type
domestic_league              63542
domestic_cup                 13514
other                         7940
international_cup             3117
national_team_competition      670
Name: count, dtype: int64

---
## Status & next steps

**Validated:**
- ✅ Dataset loads cleanly (88,783 matches, 2005–2026)
- ✅ All 8 managers found with unambiguous exact-name matches
- ✅ All managers are top-flight only — no lower-league contamination
- ✅ Big 5 filter defined: GB1, IT1, ES1, L1, FR1
- ✅ Allegri first look: 1-0 is modal scoreline (64 matches)
- ✅ `manager_matches.parquet` saved as canonical dataset

**Next:**
- Compare scoreline distributions across all 8 managers
- Plot goal-difference distributions
- Statistical test: is Allegri's distribution meaningfully different from the others?
- Consider league-level baseline: how does each manager compare to their league average?